### ISSUE TITLE
Problem with SIG testing tutorial

### ISSUE THREAD

**Issue by tjohn327** [netsec-ethz/scion-tutorials#100]
[remote_sig.zip](https://github.com/netsec-ethz/scion-tutorials/files/3193912/remote_sig.zip)

I was not able to get the SIGs to work by following the [tutorial](https://netsec-ethz.github.io/scion-tutorials/sample_projects/remote_sig/). 

But with the following changes made, I was able to communicate over SIG as described in the last part of the [tutorial](https://netsec-ethz.github.io/scion-tutorials/sample_projects/remote_sig/).

* In the sigA.config file
```
IP = "10.0.8.A" 

was changed to  

IP = "172.16.0.11"
```

* In the sigA.json file 
```
"Nets": [
                "172.16.11.0/24"
            ],

was changed to 

"Nets": [
                "172.16.12.0/24"
            ],
```

* Similary in the sigB.json file

```
"Nets": [
                "172.16.12.0/24"
            ],

was changed to 

"Nets": [
                "172.16.11.0/24"
            ],

```
* On host A, the dummy interface for the SIG to bind to, was set up as follows
```
sudo ip link add dummy11 type dummy
sudo ip addr add 172.16.0.11/32 brd + dev dummy11 label dummy11:0

```
I have attached a copy of remote_sig.md file including the changes that got the SIG working for me. Hope it helps.

**Comment by FR4NK-W** [comment]
Thank you.
Fixed as part of #144
