### ISSUE TITLE
Missing trailing slashes cause a redirect

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-tutorials#13]
The W3C Linkchecker (https://validator.w3.org/checklink) complains that many links are missing a trailing slash, and thus cause a redirect, e.g. 

Line: 745 https://netsec-ethz.github.io/scion-tutorials/virtual_machine_setup/static_ip redirected to https://netsec-ethz.github.io/scion-tutorials/virtual_machine_setup/static_ip/
    Status: 301 -> 200 OK

Shall we add trailing slashes to speed up browsing?

**Comment by hi-im-milan** [comment]
Good point. 
Is the [Commit](https://github.com/netsec-ethz/scion-tutorials/commit/531f4548df8416ba93f92e40ea2cc3715b37224a) solving that problem?

**Comment by hausheer** [comment]
No that commit fixed only a few dead links

**Comment by hi-im-milan** [comment]
Ok I'll fix it.

**Comment by hausheer** [comment]
Fixed by https://github.com/netsec-ethz/scion-tutorials/commit/796768f78d42ece5f3f3fc5a2a8cb93ec250a000
