### ISSUE TITLE
zookeeper for Android

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-tutorials#31]
@stschwar could you document - for completeness - how to install and configure zookeeper under Android?

**Comment by stschwar** [comment]
Takes some advanced steps, and the `openjdk-9-jre-headless` package in `disabled-packages` over at [termux-packages](https://github.com/termux/termux-packages) doesn't compile currently.

I will look at it later.

**Comment by mkowalski** [comment]
The latest SCION runs without zookeeper, therefore we should not recommend installing it on Android
