### ISSUE TITLE
Remove duplicate text

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-tutorials#5]
Some of the tutorials have significant overlap of the text, e.g., `ubuntu_x86_build.md` and `rpi_raspbian.md`.
Is there any possibility to avoid this duplication, either by use of macros or referencing other parts, without degrading the user experience?

**Comment by hi-im-milan** [comment]
I agree. I was thinking about making pages with less content, describing only one specific action, and then linking them. This would reduce duplicated content, but in my opinion degrade user experience as reader would have to jump around pages. It would be a really nice thing if we could actually include page content in another page, but unfortunately this framework doesn't support it. 

IMHO I would leave it as it is. It is also possible to tweak the framework so we can combine pages, but that's also a tradeoff.

**Comment by hausheer** [comment]
I think some of it will be superseded once we have the RaspberryPi Image that will include everything necessary.

**Comment by mlegner** [comment]
As discussed today, we should implement an add-on for MkDocs that allows preprocessing and macro substitution in the long run. This is not considered an urgent issue for now though.

**Comment by mkowalski** [comment]
This does not seem relevant anymore
