### ISSUE TITLE
Recommended distro for RaspberryPI

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-tutorials#7]
Currently the tutorials recommend the Raspbian distribution (i.e. Debian Stretch) for installing SCION on RaspberryPI. I noticed that Ubuntu also offers official RaspberryPi images for Ubuntu 16 core, cf. https://developer.ubuntu.com/core/get-started/raspberry-pi-2-3 @xabarass have you heard of it and what do you think about this Ubuntu distro?

**Comment by FR4NK-W** [comment]
I think it depends on whether we consider the following a reasonable additional requirement:
'''User account prerequisites

An Ubuntu SSO account is required to create the first user on an Ubuntu Core installation.

    Start by creating an Ubuntu SSO account
'''

**Comment by perrig** [comment]
Why don't we use ubuntu mate: https://ubuntu-mate.org/raspberry-pi/
There is no required account. Or we can have instructions for both?

**Comment by hausheer** [comment]
Yes, it would be great to provide instructions for all flavors. Note that the Ubuntu MATE image includes the MATE Desktop Environment, but some users may want exactly that.

**Comment by hi-im-milan** [comment]
Yes Instructions for both would be best choice, and also wouldn't be hard. For classic Ubuntu we actually don't need an account: https://wiki.ubuntu.com/ARM/RaspberryPi#Ubuntu_16.04_LTS_.27classic.27 I was able to run scion with no problems. 
On the other hand, I had some problems with Raspbian, with provided steps I wasn't able to finish build, there was a problem with installing all dependencies. Maybe on Monday I could ask somebody if I missed something.

Also I found this repo: https://github.com/TheSin-/rpi-img-builder It allows really cool way of building RPI images with different distributions. Nicely organized and easy to follow. What do you think?

**Comment by perrig** [comment]
If I recall correctly, only one Python dependency was missing, nose-cov or
something like that. @FR4NK mentioned that the system works also if that
dependency is simply removed.

The image builder looks good!

**Comment by hausheer** [comment]
Yes, removing the python3-nose-cov dependency works!

**Comment by hi-im-milan** [comment]
Hm, I have tried removing `python3-nose-cov` package that solved problem with debian packages, but then pip3 started complaining that hashes for some packages do not match with hashes specified in requirements file. I am running everything on Raspbian stretch. Am I missing something?

**Comment by mkowalski** [comment]
Tutorials do not mention Raspberry Pi at this moment. Closing the issue
