### ISSUE TITLE
Add Troubleshooting Guide

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scion-tutorials#74]
Following up on [this mailing list discussion](https://groups.google.com/forum/#!topic/scion-community/1lZ9u6DNVYI).

Add a troubleshooting guide. At least the following points should be covered:

> verify that:
>  *  the AS is active in the coordinator.
>  *  the system clock is correct (+-5s is okay, +-1min is not).
>  *  the vpn tunnel is established via `ip a`. 

Ideally we'd have a small diagnosing script that checks all common problems.

**Comment by matzf** [comment]
Note: I just came across the [`htpdate`](http://www.vervest.org/htp/) tool, which determines a time offset based on HTTP header information. Once installed (ubuntu: `apt install htpdate`), it can be used with any normal webserver, e.g.:
```
$ htpdate -q gnu.org cloudflare.com scionlab.org www.inf.ethz.ch google.com
No time correction needed
```
This seems useful in cases where `ntp` fails due to firewalls or other network problems.

**Comment by juagargi** [comment]
+1 to the `htpdate` tool. We have suggested already using www.google.com for users behind firewalls.

There is a troubleshooting guide on its way. We will revisit this ticket once we publish it, to ensure the three items @matzf mentions are covered.

**Comment by matzf** [comment]
Just one more note on the `htpdate` tool: the feature of this tool that we're interested, i.e. displaying a very rough guess for the time offset for diagnostics, can also trivially be implemented in bash or python, no need for an additional dependency; the only thing the tool does is make a HEAD request to a webserver and parse the `Date:` field.
E.g. in bash
 ```bash
tl=$(date '+%s')
ts=$(date '+%s' --date="$(curl -sI scionlab.org | sed -n  '/Date:\s*/s///p')")
let diff=$ts-$tl
echo Time diff: "$diff"s
```
As a oneliner for copy-pasta:
```bash
tl=$(date '+%s'); ts=$(date '+%s' --date="$(curl -sI scionlab.org | sed -n  '/Date:\s*/s///p')"); let diff=$ts-$tl; echo Time diff: "$diff"s
```
